import { render, screen, cleanup } from "@testing-library/react";
import { afterEach, describe, expect, it } from "vitest";

import { IntelligencePanel } from "@/components/workspace/intelligence-panel";
import type {
  ApplicationDoc,
  Archetype,
  CandidateValidationReport,
  ModuleKey,
  ModuleState,
} from "@/lib/firestore";

afterEach(() => cleanup());

const _emptyModules = (): Record<ModuleKey, ModuleState> => {
  const keys: ModuleKey[] = [
    "benchmark",
    "gaps",
    "learningPlan",
    "cv",
    "coverLetter",
    "personalStatement",
    "portfolio",
    "scorecard",
  ];
  const out = {} as Record<ModuleKey, ModuleState>;
  for (const k of keys) out[k] = { state: "idle", updatedAt: 0 };
  return out;
};

const _baseApp = (overrides: Partial<ApplicationDoc> = {}): ApplicationDoc => ({
  id: "app-1",
  userId: "u-1",
  title: "Test",
  status: "draft",
  createdAt: 0,
  updatedAt: 0,
  modules: _emptyModules(),
  ...overrides,
});

const _arch = (overrides: Partial<Archetype> = {}): Archetype => ({
  name: "Stripe Senior Eng",
  must_have_skills: ["python"],
  nice_to_have_skills: [],
  years_min: 5,
  years_max: 8,
  salary_band: { p50: 240000 },
  cultural_signals: [],
  ...overrides,
});

const _validation = (
  overrides: Partial<CandidateValidationReport> = {},
): CandidateValidationReport => ({
  claims: [
    { claim: "5y python", validator: "github_commits", status: "verified", detail: "" },
  ],
  verified_count: 1,
  conflicted_count: 0,
  ...overrides,
});

describe("IntelligencePanel — ATLAS extras (Slice F3)", () => {
  it("renders the panel without ATLAS extras when no archetypes/validation exist", () => {
    render(
      <IntelligencePanel
        app={_baseApp()}
        keywordCount={0}
        missingCount={0}
        evidenceCount={0}
      />,
    );
    // Existing 'no evidence linked' insight always renders, so the
    // panel itself is non-empty — but the ATLAS extras block is absent.
    expect(screen.queryByTestId("atlas-archetype-panel")).not.toBeInTheDocument();
    expect(screen.queryByTestId("atlas-validation-panel")).not.toBeInTheDocument();
  });

  it("does NOT render the ATLAS extras block when neither archetypes nor validation exist", () => {
    render(
      <IntelligencePanel
        app={_baseApp()}
        keywordCount={3}
        missingCount={0}
        evidenceCount={0}
      />,
    );
    expect(screen.queryByTestId("atlas-archetype-panel")).not.toBeInTheDocument();
    expect(screen.queryByTestId("atlas-validation-panel")).not.toBeInTheDocument();
  });

  it("renders ArchetypePanel when archetypes are present on benchmark", () => {
    render(
      <IntelligencePanel
        app={_baseApp({
          benchmark: {
            keywords: [],
            idealSkills: [],
            rubric: [],
            dimensions: [],
            archetypes: [_arch(), _arch({ name: "Stripe Staff" })],
          },
        })}
        keywordCount={0}
        missingCount={0}
        evidenceCount={0}
      />,
    );
    expect(screen.getByTestId("atlas-archetype-panel")).toBeInTheDocument();
    expect(screen.getAllByTestId("atlas-archetype-card")).toHaveLength(2);
  });

  it("emits the archetype-count insight line when archetypes are present", () => {
    render(
      <IntelligencePanel
        app={_baseApp({
          benchmark: {
            keywords: [],
            idealSkills: [],
            rubric: [],
            dimensions: [],
            archetypes: [_arch(), _arch({ name: "B" }), _arch({ name: "C" })],
          },
        })}
        keywordCount={0}
        missingCount={0}
        evidenceCount={0}
      />,
    );
    expect(
      screen.getByText("3 target archetypes generated by ATLAS"),
    ).toBeInTheDocument();
  });

  it("renders CandidateValidationPanel when meta.atlas_candidate_validation has claims", () => {
    render(
      <IntelligencePanel
        app={_baseApp({
          meta: { atlas_candidate_validation: _validation() },
        })}
        keywordCount={0}
        missingCount={0}
        evidenceCount={0}
      />,
    );
    expect(screen.getByTestId("atlas-validation-panel")).toBeInTheDocument();
  });

  it("emits an emerald 'verified' insight line when no conflicts", () => {
    render(
      <IntelligencePanel
        app={_baseApp({
          meta: {
            atlas_candidate_validation: _validation({
              claims: [
                { claim: "a", validator: "x", status: "verified", detail: "" },
                { claim: "b", validator: "x", status: "verified", detail: "" },
              ],
              verified_count: 2,
              conflicted_count: 0,
            }),
          },
        })}
        keywordCount={0}
        missingCount={0}
        evidenceCount={0}
      />,
    );
    expect(screen.getByText("Claim validation: 2/2 verified")).toBeInTheDocument();
  });

  it("emits a red conflict-aware insight line when conflicted_count > 0", () => {
    render(
      <IntelligencePanel
        app={_baseApp({
          meta: {
            atlas_candidate_validation: _validation({
              claims: [
                { claim: "a", validator: "x", status: "verified", detail: "" },
                { claim: "b", validator: "x", status: "conflicted", detail: "" },
                { claim: "c", validator: "x", status: "conflicted", detail: "" },
              ],
              verified_count: 1,
              conflicted_count: 2,
            }),
          },
        })}
        keywordCount={0}
        missingCount={0}
        evidenceCount={0}
      />,
    );
    expect(
      screen.getByText("Claim validation: 1/3 verified — 2 conflicts"),
    ).toBeInTheDocument();
  });

  it("renders BOTH panels when both archetypes and validation are present", () => {
    render(
      <IntelligencePanel
        app={_baseApp({
          benchmark: {
            keywords: [],
            idealSkills: [],
            rubric: [],
            dimensions: [],
            archetypes: [_arch()],
          },
          meta: { atlas_candidate_validation: _validation() },
        })}
        keywordCount={0}
        missingCount={0}
        evidenceCount={0}
      />,
    );
    expect(screen.getByTestId("atlas-archetype-panel")).toBeInTheDocument();
    expect(screen.getByTestId("atlas-validation-panel")).toBeInTheDocument();
  });

  it("renders the ATLAS extras block even when there are zero non-ATLAS insights", () => {
    // i.e. an app with only archetypes and nothing else should still
    // skip the empty-placeholder branch.
    render(
      <IntelligencePanel
        app={_baseApp({
          benchmark: {
            keywords: [],
            idealSkills: [],
            rubric: [],
            dimensions: [],
            archetypes: [_arch()],
          },
        })}
        keywordCount={0}
        missingCount={0}
        evidenceCount={0}
      />,
    );
    expect(screen.queryByText(/will appear here once modules are generated/i))
      .not.toBeInTheDocument();
    expect(screen.getByTestId("atlas-archetype-panel")).toBeInTheDocument();
  });

  it("ignores archetypes when the field is not an array", () => {
    render(
      <IntelligencePanel
        app={_baseApp({
          benchmark: {
            keywords: [],
            idealSkills: [],
            rubric: [],
            dimensions: [],
            // intentional shape violation — TS-cast for the test
            archetypes: "not-an-array" as unknown as Archetype[],
          },
        })}
        keywordCount={0}
        missingCount={0}
        evidenceCount={0}
      />,
    );
    expect(screen.queryByTestId("atlas-archetype-panel")).not.toBeInTheDocument();
    expect(
      screen.queryByText(/target archetype/i),
    ).not.toBeInTheDocument();
  });
});
