import type { Metadata } from "next";
import Link from "next/link";
import { Sparkles } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "HireStack AI Terms of Service — the rules governing use of the platform.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Minimal header */}
      <header className="border-b">
        <div className="mx-auto flex h-16 max-w-4xl items-center justify-between px-4">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-gradient-to-br from-primary to-violet-600">
              <Sparkles className="h-4 w-4 text-white" />
            </div>
            <span className="text-base font-bold">
              HireStack <span className="text-primary">AI</span>
            </span>
          </Link>
          <Link href="/" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
            ← Back to home
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-4 py-16">
        <h1 className="text-4xl font-bold tracking-tight">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">Last updated: April 2025</p>

        <div className="mt-10 space-y-10 text-sm leading-relaxed text-foreground/90">
          <section>
            <h2 className="text-xl font-semibold mb-3">1. Acceptance of terms</h2>
            <p>
              By creating an account or using HireStack AI (&ldquo;the Service&rdquo;), you agree to these
              Terms of Service. If you do not agree, do not use the Service. These terms form a binding
              agreement between you and HireStack AI.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">2. Description of service</h2>
            <p>
              HireStack AI provides an AI-powered platform to help users create tailored job application
              documents, analyse skill gaps, and prepare for interviews. The Service includes document
              generation, ATS scanning, salary intelligence, and related career tools.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">3. Accounts</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>You must be 16 years or older to create an account.</li>
              <li>You are responsible for maintaining the security of your account credentials.</li>
              <li>You must provide accurate information when registering.</li>
              <li>
                You are responsible for all activity that occurs under your account.
              </li>
              <li>One person may not maintain more than one free account.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">4. Acceptable use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>Use the Service to generate false, misleading, or fraudulent application materials.</li>
              <li>Attempt to reverse-engineer, scrape, or extract data from the Service at scale.</li>
              <li>Upload content that violates intellectual property rights or applicable law.</li>
              <li>Use the Service to harass, harm, or discriminate against others.</li>
              <li>Attempt to circumvent rate limits, authentication, or billing controls.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">5. AI-generated content</h2>
            <p>
              Documents generated by HireStack AI are tools to assist you, not substitutes for your own
              professional judgement. You are solely responsible for reviewing all AI-generated content
              before submitting it to employers. HireStack AI makes no guarantees about employment
              outcomes, interview success, or job placement.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">6. Intellectual property</h2>
            <p>
              You retain ownership of the resume data and documents you upload. You grant HireStack AI a
              limited licence to process your content solely to provide the Service. HireStack AI retains
              all rights to its platform, AI models, and generated template structures.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">7. Plans and billing</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>The Free plan is available at no charge with usage limits.</li>
              <li>Paid plans are billed monthly or annually as selected at checkout.</li>
              <li>All fees are non-refundable except where required by law.</li>
              <li>
                We reserve the right to change pricing with 30 days&apos; notice to active subscribers.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">8. Termination</h2>
            <p>
              You may close your account at any time via Settings. We may suspend or terminate accounts
              that violate these terms. Upon termination, your right to use the Service ceases immediately
              and your data will be deleted within 30 days.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">9. Disclaimers</h2>
            <p>
              The Service is provided &ldquo;as is&rdquo; without warranties of any kind. We do not warrant that
              the Service will be error-free, uninterrupted, or that AI-generated content will be accurate
              or suitable for any particular purpose.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">10. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, HireStack AI shall not be liable for any indirect,
              incidental, consequential, or punitive damages arising from your use of the Service. Our
              total liability to you shall not exceed the amount you paid us in the 12 months preceding
              the claim.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">11. Governing law</h2>
            <p>
              These terms are governed by the laws of the jurisdiction in which HireStack AI is incorporated,
              without regard to conflict-of-law provisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">12. Changes to terms</h2>
            <p>
              We may update these terms at any time. We will notify you of material changes via email or
              an in-app notice. Continued use after changes take effect constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">13. Contact</h2>
            <p>
              Questions about these terms? Contact us at{" "}
              <a href="mailto:legal@hirestack.tech" className="text-primary underline">
                legal@hirestack.tech
              </a>.
            </p>
          </section>
        </div>

        <div className="mt-16 border-t pt-8 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-muted-foreground">
          <p>© {new Date().getFullYear()} HireStack AI. All rights reserved.</p>
          <div className="flex gap-4">
            <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy Policy</Link>
            <Link href="/" className="hover:text-foreground transition-colors">Home</Link>
          </div>
        </div>
      </main>
    </div>
  );
}
