"use client";

import { Briefcase, DollarSign, Sparkles, Target } from "lucide-react";
import { cn } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import type { Archetype } from "@/lib/firestore";

/**
 * ArchetypePanel — renders the up-to-3 dynamic role archetypes
 * generated by ATLAS v2's `ArchetypeGenerator` (see
 * `ai_engine/agents/sub_agents/atlas/dynamic_archetypes.py`).
 *
 * Each archetype is rendered as a card with:
 *   • name (header)
 *   • years range
 *   • salary band p25/p50/p75 (when present)
 *   • must-have skills (emphasised)
 *   • nice-to-have skills (muted)
 *   • cultural signals
 *
 * Renders `null` (no DOM) when `archetypes` is undefined or
 * empty, so the panel can be unconditionally mounted by parents
 * — it'll only appear once the upstream
 * `ATLAS_DYNAMIC_ARCHETYPES_ENABLED` flag is on AND the SSE
 * complete payload carried at least one archetype.
 */
export function ArchetypePanel({
  archetypes,
  className,
}: {
  archetypes?: Archetype[] | null;
  className?: string;
}) {
  const list = Array.isArray(archetypes) ? archetypes.filter(Boolean) : [];
  if (list.length === 0) return null;

  return (
    <section
      data-testid="atlas-archetype-panel"
      className={cn("space-y-3", className)}
      aria-label="Dynamic role archetypes"
    >
      <header className="flex items-center gap-2">
        <Sparkles className="h-4 w-4 text-violet-600" aria-hidden />
        <h3 className="text-sm font-semibold tracking-tight">
          Target archetypes
        </h3>
        <span className="text-xs text-muted-foreground">
          ({list.length} generated)
        </span>
      </header>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        {list.map((arch, i) => (
          <ArchetypeCard key={`${arch.name}-${i}`} archetype={arch} />
        ))}
      </div>
    </section>
  );
}

function ArchetypeCard({ archetype }: { archetype: Archetype }) {
  const yearsLo =
    typeof archetype.years_min === "number" ? archetype.years_min : undefined;
  const yearsHi =
    typeof archetype.years_max === "number" ? archetype.years_max : undefined;
  const showYears =
    yearsLo !== undefined && yearsHi !== undefined && (yearsLo > 0 || yearsHi > 0);

  const salary = archetype.salary_band ?? {};
  const hasSalary = Object.keys(salary).length > 0;

  const must = Array.isArray(archetype.must_have_skills) ? archetype.must_have_skills : [];
  const nice = Array.isArray(archetype.nice_to_have_skills) ? archetype.nice_to_have_skills : [];
  const cultural = Array.isArray(archetype.cultural_signals) ? archetype.cultural_signals : [];

  return (
    <article
      data-testid="atlas-archetype-card"
      className="rounded-lg border bg-card p-3 space-y-2.5 shadow-sm"
    >
      <header className="flex items-start justify-between gap-2">
        <h4 className="text-sm font-semibold leading-tight">{archetype.name}</h4>
        {showYears && (
          <Badge
            variant="secondary"
            className="text-[10px] shrink-0 bg-blue-500/10 text-blue-700 border-blue-200 border"
          >
            <Briefcase className="h-3 w-3 mr-1" aria-hidden />
            {yearsLo}–{yearsHi}y
          </Badge>
        )}
      </header>

      {hasSalary && (
        <div
          data-testid="atlas-archetype-salary"
          className="flex items-center gap-2 text-xs text-muted-foreground"
        >
          <DollarSign className="h-3 w-3" aria-hidden />
          <span>
            p25 {formatMoney(salary.p25)} · p50 {formatMoney(salary.p50)} · p75{" "}
            {formatMoney(salary.p75)}
          </span>
        </div>
      )}

      {must.length > 0 && (
        <div>
          <div className="flex items-center gap-1.5 text-[11px] font-medium text-muted-foreground mb-1">
            <Target className="h-3 w-3" aria-hidden />
            Must have
          </div>
          <div className="flex flex-wrap gap-1">
            {must.slice(0, 12).map((s) => (
              <Badge
                key={s}
                variant="secondary"
                className="text-[10px] bg-emerald-500/10 text-emerald-700 border border-emerald-200"
              >
                {s}
              </Badge>
            ))}
          </div>
        </div>
      )}

      {nice.length > 0 && (
        <div>
          <div className="text-[11px] font-medium text-muted-foreground mb-1">
            Nice to have
          </div>
          <div className="flex flex-wrap gap-1">
            {nice.slice(0, 8).map((s) => (
              <Badge
                key={s}
                variant="outline"
                className="text-[10px] text-muted-foreground"
              >
                {s}
              </Badge>
            ))}
          </div>
        </div>
      )}

      {cultural.length > 0 && (
        <div className="text-[11px] text-muted-foreground italic">
          {cultural.slice(0, 4).join(" · ")}
        </div>
      )}

      {archetype.rationale && (
        <div
          data-testid="atlas-archetype-rationale"
          className="text-[11px] text-muted-foreground border-t pt-2"
        >
          {archetype.rationale}
        </div>
      )}
    </article>
  );
}

function formatMoney(v: number | string | undefined): string {
  const n = typeof v === "string" ? Number(v) : v;
  if (typeof n !== "number" || !Number.isFinite(n) || n <= 0) return "—";
  if (n >= 1000) return `$${Math.round(n / 1000)}k`;
  return `$${n}`;
}
