/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Emitted when a new source (article, transcript, doc) is added to the AIM library.
 */
export interface AimSourceCreatedV1 {
  event_type: "aim.source.created";
  event_version: 1;
  payload: {
    source_id: string;
    kind: "article" | "video" | "podcast" | "doc" | "other";
    title?: string | null;
    url?: string | null;
  };
}
