/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Emitted when a learner picks up an AIM assignment.
 */
export interface AimAssignmentCreatedV1 {
  event_type: "aim.assignment.created";
  event_version: 1;
  payload: {
    assignment_id: string;
    module_id: string;
    user_id: string;
    due_at?: string | null;
  };
}
