/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Canonical wrapper around every domain event. Mirrors backend/app/core/events/envelope.py.
 */
export interface EventEnvelope {
  /**
   * UUIDv4 generated at emit time.
   */
  event_id: string;
  /**
   * Dotted lower-snake-case identifier, e.g. ``generation.completed``.
   */
  event_type: string;
  event_version: number;
  org_id: string;
  /**
   * RFC3339 with timezone (UTC). Naive timestamps are rejected.
   */
  occurred_at: string;
  idempotency_key?: string | null;
  payload: {
    [k: string]: unknown;
  };
}
