/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Emitted when an application's generation pipeline is enqueued.
 */
export interface GenerationRequestedV1 {
  event_type: "generation.requested";
  event_version: 1;
  payload: {
    job_id: string;
    application_id: string;
    user_id: string;
    /**
     * @minItems 1
     */
    requested_modules: [string, ...string[]];
  };
}
