/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Emitted when the generation pipeline reaches a terminal state (success or failure).
 */
export interface GenerationCompletedV1 {
  event_type: "generation.completed";
  event_version: 1;
  payload: {
    job_id: string;
    application_id: string;
    user_id: string;
    status: "succeeded" | "failed" | "cancelled";
    duration_ms?: number | null;
    error_class?: string | null;
  };
}
