/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Emitted when a new mission draft is created (by user or by an agent).
 */
export interface MissionDraftCreatedV1 {
  event_type: "mission.draft.created";
  event_version: 1;
  payload: {
    mission_id: string;
    draft_id: string;
    author: "user" | "agent";
    title?: string | null;
  };
}
