"""Tests for ``scripts/ops/dlq_replay.py`` (m11-pr37)."""
from __future__ import annotations

import importlib.util
import io
import json
import sys
import time
from contextlib import redirect_stdout
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
SCRIPT = REPO_ROOT / "scripts" / "ops" / "dlq_replay.py"


def _load_module():
    spec = importlib.util.spec_from_file_location("dlq_replay_under_test", SCRIPT)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


dlq_replay = _load_module()


# ─────────────────────────── fake redis ───────────────────────────


class _FakeRedis:
    """Tiny synchronous Redis-stream stub.

    Implements just enough of XRANGE / XADD / XDEL for the script.
    Stream entries are stored as ``(msg_id, fields_dict)`` lists keyed
    by stream name. Auto-incrementing msg_ids of the form ``<ms>-N`` are
    generated by ``xadd`` unless ``msg_id`` is provided via ``_seed``.
    """

    def __init__(self) -> None:
        self.streams: dict[str, list[tuple[str, dict[str, str]]]] = {}
        self._seq = 0

    def ping(self) -> bool:
        return True

    def _next_id(self) -> str:
        self._seq += 1
        return f"{int(time.time() * 1000)}-{self._seq}"

    def xadd(self, stream: str, fields: dict[str, str]) -> str:
        mid = self._next_id()
        self.streams.setdefault(stream, []).append((mid, dict(fields)))
        return mid

    def _seed(self, stream: str, mid: str, fields: dict[str, str]) -> None:
        self.streams.setdefault(stream, []).append((mid, dict(fields)))

    def xrange(self, stream, *, min="-", max="+", count=None):
        entries = list(self.streams.get(stream, []))
        if min != "-":
            entries = [e for e in entries if e[0] >= min]
        if max != "+":
            entries = [e for e in entries if e[0] <= max]
        if count is not None:
            entries = entries[:count]
        return entries

    def xdel(self, stream: str, mid: str) -> int:
        before = len(self.streams.get(stream, []))
        self.streams[stream] = [(m, f) for m, f in self.streams.get(stream, []) if m != mid]
        return before - len(self.streams.get(stream, []))


# ─────────────────────────── fixtures ───────────────────────────


@pytest.fixture
def redis_with_entries():
    r = _FakeRedis()
    # Generic-consumer entry (has 'event' field).
    r._seed(
        dlq_replay.DLQ_STREAM,
        "1000-1",
        {
            "consumer": "outbox-relay",
            "source_stream": "events:aim.source.created",
            "source_msg_id": "999-1",
            "reason": "handler raised: NoCreditsError",
            "event": json.dumps(
                {
                    "event_id": "evt-abc",
                    "event_type": "aim.source.created",
                    "event_version": 1,
                    "payload": {"source_id": "src-xyz"},
                }
            ),
        },
    )
    # Queue entry (no 'event' field — has job_id/user_id).
    r._seed(
        dlq_replay.DLQ_STREAM,
        "2000-1",
        {
            "consumer": "hirestack-workers",
            "source_stream": "generation:jobs",
            "source_msg_id": "1500-1",
            "job_id": "job-42",
            "user_id": "user-7",
            "reason": "max_deliveries_exceeded (6>5)",
        },
    )
    return r


def _run(args_func, redis):
    buf = io.StringIO()
    with redirect_stdout(buf):
        rc = int(args_func(redis))
    return rc, buf.getvalue()


# ─────────────────────────── parse helpers ───────────────────────────


def test_parse_since_dash_means_all():
    assert dlq_replay._parse_since("-") == "-"
    assert dlq_replay._parse_since(None) == "-"


def test_parse_since_durations():
    out = dlq_replay._parse_since("15m")
    ms = int(out.split("-")[0])
    assert ms <= int(time.time() * 1000) - 14 * 60 * 1000


def test_parse_since_bare_epoch():
    assert dlq_replay._parse_since("1700000000000") == "1700000000000-0"


def test_parse_since_bad_input(capsys):
    with pytest.raises(SystemExit) as exc:
        dlq_replay._parse_since("garbage")
    assert exc.value.code == 3


def test_matches_filters():
    f = {"consumer": "x", "reason": "Boom because of NoCredits"}
    assert dlq_replay._matches_filters(f, consumer="x", reason_substr="nocredits")
    assert not dlq_replay._matches_filters(f, consumer="y", reason_substr=None)
    assert not dlq_replay._matches_filters(f, consumer=None, reason_substr="missing")


# ─────────────────────────── list / inspect ───────────────────────────


def test_list_all(redis_with_entries):
    args = type("A", (), {"consumer": None, "reason": None, "since": "-", "limit": 50})()
    rc, out = _run(lambda r: dlq_replay.cmd_list(r, args), redis_with_entries)
    assert rc == 0
    assert "1000-1" in out and "2000-1" in out
    assert "outbox-relay" in out and "hirestack-workers" in out


def test_list_filtered_by_consumer(redis_with_entries):
    args = type(
        "A", (), {"consumer": "hirestack-workers", "reason": None, "since": "-", "limit": 50}
    )()
    rc, out = _run(lambda r: dlq_replay.cmd_list(r, args), redis_with_entries)
    assert rc == 0
    assert "2000-1" in out and "1000-1" not in out


def test_inspect_decodes_event_json(redis_with_entries):
    args = type("A", (), {"msg_id": "1000-1"})()
    rc, out = _run(lambda r: dlq_replay.cmd_inspect(r, args), redis_with_entries)
    assert rc == 0
    parsed = json.loads(out)
    assert parsed["dlq_msg_id"] == "1000-1"
    assert parsed["event"]["event_id"] == "evt-abc"


def test_inspect_not_found(redis_with_entries):
    args = type("A", (), {"msg_id": "9999-9"})()
    rc, _ = _run(lambda r: dlq_replay.cmd_inspect(r, args), redis_with_entries)
    assert rc == 1


# ─────────────────────────── replay payload ───────────────────────────


def test_build_replay_payload_generic_consumer():
    fields = {"event": json.dumps({"event_id": "x", "payload": {"k": 1}})}
    payload = dlq_replay._build_replay_payload(fields)
    assert payload["event_id"] == "x"
    # nested objects stringified for stream-field compat
    assert json.loads(payload["payload"]) == {"k": 1}


def test_build_replay_payload_queue():
    fields = {"job_id": "j1", "user_id": "u1"}
    assert dlq_replay._build_replay_payload(fields) == {"job_id": "j1", "user_id": "u1"}


def test_build_replay_payload_unknown_shape():
    with pytest.raises(ValueError):
        dlq_replay._build_replay_payload({"reason": "oops"})


# ─────────────────────────── replay (dry-run + apply) ───────────────────────────


def test_replay_dry_run_does_not_mutate(redis_with_entries):
    args = type("A", (), {"msg_id": "1000-1", "apply": False, "keep": False})()
    rc, out = _run(lambda r: dlq_replay.cmd_replay(r, args), redis_with_entries)
    assert rc == 0
    assert "DRY RUN" in out and "WOULD XADD" in out
    # nothing changed
    assert len(redis_with_entries.streams[dlq_replay.DLQ_STREAM]) == 2
    assert "events:aim.source.created" not in redis_with_entries.streams


def test_replay_apply_mutates_and_purges(redis_with_entries):
    args = type("A", (), {"msg_id": "1000-1", "apply": True, "keep": False})()
    rc, out = _run(lambda r: dlq_replay.cmd_replay(r, args), redis_with_entries)
    assert rc == 0
    assert "DID XADD" in out
    # source stream got the event back
    src = redis_with_entries.streams["events:aim.source.created"]
    assert len(src) == 1
    assert src[0][1]["event_id"] == "evt-abc"
    # DLQ entry purged
    assert all(mid != "1000-1" for mid, _ in redis_with_entries.streams[dlq_replay.DLQ_STREAM])


def test_replay_apply_keep_does_not_purge(redis_with_entries):
    args = type("A", (), {"msg_id": "2000-1", "apply": True, "keep": True})()
    rc, _ = _run(lambda r: dlq_replay.cmd_replay(r, args), redis_with_entries)
    assert rc == 0
    assert any(mid == "2000-1" for mid, _ in redis_with_entries.streams[dlq_replay.DLQ_STREAM])
    assert "generation:jobs" in redis_with_entries.streams


def test_replay_not_found(redis_with_entries):
    args = type("A", (), {"msg_id": "9999-9", "apply": True, "keep": False})()
    rc, _ = _run(lambda r: dlq_replay.cmd_replay(r, args), redis_with_entries)
    assert rc == 1


# ─────────────────────────── replay-all ───────────────────────────


def test_replay_all_filters_by_consumer(redis_with_entries):
    args = type(
        "A",
        (),
        {
            "consumer": "outbox-relay",
            "reason": None,
            "since": "-",
            "limit": 100,
            "apply": True,
            "keep": False,
        },
    )()
    rc, out = _run(lambda r: dlq_replay.cmd_replay_all(r, args), redis_with_entries)
    assert rc == 0
    assert "REPLAYING 1 entries" in out
    # outbox-relay entry replayed + purged; queue entry untouched
    remaining = redis_with_entries.streams[dlq_replay.DLQ_STREAM]
    assert {mid for mid, _ in remaining} == {"2000-1"}
    assert "events:aim.source.created" in redis_with_entries.streams


def test_replay_all_dry_run(redis_with_entries):
    args = type(
        "A",
        (),
        {
            "consumer": None,
            "reason": None,
            "since": "-",
            "limit": 100,
            "apply": False,
            "keep": False,
        },
    )()
    rc, out = _run(lambda r: dlq_replay.cmd_replay_all(r, args), redis_with_entries)
    assert rc == 0
    assert "DRY RUN" in out
    assert len(redis_with_entries.streams[dlq_replay.DLQ_STREAM]) == 2


# ─────────────────────────── purge ───────────────────────────


def test_purge_dry_run(redis_with_entries):
    args = type("A", (), {"msg_id": "1000-1", "apply": False})()
    rc, out = _run(lambda r: dlq_replay.cmd_purge(r, args), redis_with_entries)
    assert rc == 0
    assert "DRY RUN" in out
    assert len(redis_with_entries.streams[dlq_replay.DLQ_STREAM]) == 2


def test_purge_apply(redis_with_entries):
    args = type("A", (), {"msg_id": "1000-1", "apply": True})()
    rc, _ = _run(lambda r: dlq_replay.cmd_purge(r, args), redis_with_entries)
    assert rc == 0
    assert all(mid != "1000-1" for mid, _ in redis_with_entries.streams[dlq_replay.DLQ_STREAM])


def test_purge_not_found(redis_with_entries):
    args = type("A", (), {"msg_id": "nope", "apply": True})()
    rc, _ = _run(lambda r: dlq_replay.cmd_purge(r, args), redis_with_entries)
    assert rc == 1


# ─────────────────────────── CLI parser ───────────────────────────


def test_parser_requires_subcommand():
    parser = dlq_replay._build_parser()
    with pytest.raises(SystemExit):
        parser.parse_args([])


def test_parser_replay_apply_flag():
    parser = dlq_replay._build_parser()
    ns = parser.parse_args(["replay", "1-1", "--apply"])
    assert ns.cmd == "replay" and ns.apply is True and ns.keep is False
